/* ===========================
   Step 1: Database Setup
   =========================== */

-- Database setup
USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE SOURCES;
CREATE OR REPLACE SCHEMA SOURCES.RAW;
CREATE OR REPLACE DATABASE DEV;
CREATE OR REPLACE DATABASE PROD;

/* ===========================
   Step 2: Raw Data Load
   =========================== */

-- Create a stage in Snowflake that points to the Azure Blob Storage container
CREATE OR REPLACE STAGE SOURCES.RAW.EUROVISION_STAGE
URL = 'azure://snowflakedemostorage.blob.core.windows.net/eurovision';

-- Create raw tables
CREATE OR REPLACE TABLE SOURCES.RAW.CONTESTANTS (
  YEAR VARCHAR,
  COUNTRY VARCHAR,
  COMPOSERS VARCHAR,
  LYRICISTS VARCHAR,
  LYRICS VARCHAR,
  SONG VARCHAR,
  PERFORMER VARCHAR,
  YOUTUBE_URL VARCHAR,
  SEMIFINAL_NUMBER VARCHAR,
  SEMIFINAL_RUNNING_ORDER VARCHAR,
  SEMIFINAL_JURY_POINTS VARCHAR,
  SEMIFINAL_TELEVOTING_POINTS VARCHAR,
  SEMIFINAL_TOTAL_POINTS VARCHAR,
  SEMIFINAL_PLACE VARCHAR,
  FINAL_RUNNING_ORDER VARCHAR,
  FINAL_JURY_POINTS VARCHAR,
  FINAL_TELEVOTING_POINTS VARCHAR,
  FINAL_TOTAL_POINTS VARCHAR
);

CREATE OR REPLACE TABLE SOURCES.RAW.VOTES (
  YEAR VARCHAR,
  ROUND VARCHAR,
  FROM_COUNTRY VARCHAR,
  TO_COUNTRY VARCHAR,
  TOTAL_POINTS VARCHAR,
  TELEVOTING_POINTS VARCHAR,
  JURY_POINTS VARCHAR
);

CREATE OR REPLACE TABLE SOURCES.RAW.JURORS (
  YEAR VARCHAR,
  ROUND VARCHAR,
  FROM_COUNTRY VARCHAR,
  A VARCHAR,
  B VARCHAR,
  C VARCHAR,
  D VARCHAR,
  E VARCHAR,
  TO_COUNTRY VARCHAR
);

CREATE OR REPLACE TABLE SOURCES.RAW.COUNTRIES (
  COUNTRY VARCHAR,
  COUNTRY_NAME VARCHAR,
  REGION VARCHAR
);

CREATE OR REPLACE TABLE SOURCES.RAW.BOOKMAKERS (
  YEAR VARCHAR,
  ROUND VARCHAR,
  COUNTRY VARCHAR,
  BOOKMAKER VARCHAR,
  ODDS VARCHAR
);

CREATE TABLE SOURCES.RAW.BETTING_OFFICES (
  BETTING_BM_ID VARCHAR,
  BETTING_SC_ID VARCHAR,
  BETTING_NAME VARCHAR,
  BETTING_SCORE VARCHAR,
  YEAR VARCHAR,
  PERFORMER VARCHAR,
  SONG VARCHAR,
  PAGE_URL VARCHAR,
  CONTEST_ROUND VARCHAR,
  COUNTRY_NAME VARCHAR,
  COUNTRY_CODE VARCHAR
);

-- Load data into raw tables
COPY INTO SOURCES.RAW.CONTESTANTS
FROM @SOURCES.RAW.EUROVISION_STAGE/contestants.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1);

COPY INTO SOURCES.RAW.VOTES
FROM @SOURCES.RAW.EUROVISION_STAGE/votes.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1);

COPY INTO SOURCES.RAW.JURORS
FROM @SOURCES.RAW.EUROVISION_STAGE/jurors.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1);

COPY INTO SOURCES.RAW.COUNTRIES
FROM @SOURCES.RAW.EUROVISION_STAGE/countries.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1);

COPY INTO SOURCES.RAW.BOOKMAKERS
FROM @SOURCES.RAW.EUROVISION_STAGE/bookmakers.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1);

COPY INTO SOURCES.RAW.BETTING_OFFICES
FROM @SOURCES.RAW.EUROVISION_STAGE/betting_offices.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1);